# Generated by Django 5.0.7 on 2024-07-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
                ('hobbies', models.TextField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
